Adds Conditional Compilation Statements to the AST
rokucommunity/brighterscript pull request #1149
Opened 2024-04-29 19:16 UTC by markwpearce

Conditional compile directives (`#if`, `#const`, `#error`, etc.) are now part of the AST, and as such, the branches of the condition compiles can be walked.

There is one concession with this: `#if` blocks are treated as any other block, and everything in them must be self contained, or will cause a diagnostic.

That means that even though this is allowed in Brightscript:
```
sub foo()
# if true
end sub
#end if
```

it will cause some diagnostics, because the `sub foo()` is partially inside and outside the `#if` statement

[] TODO - Add some walk mode options that allow walking the tree based on true/false const values.

2024-05-10 16:51 UTC, markwpearce commented
I suppose we should support `#if not <bs_const>` as well? #1158

2024-05-10 16:55 UTC, TwitchBronBron commented
> I suppose we should support `#if not <bs_const>` as well? #1158

Yes, if we can!

2024-05-14 18:47 UTC, TwitchBronBron requested changes

2024-05-14 18:47 UTC, TwitchBronBron commented on src/parser/Statement.ts
> +            let conditionTrue = options.bsConsts?.get(this.tokens.condition.text.toLowerCase());
Shouldn't we fall back to the parent bsConsts if not provided?
```typescript
const bsConsts = options.bsConsts ?? this.getBsConsts();
```
That way it supports calling .walk on any ast node.

2024-05-15 15:12 UTC, TwitchBronBron approved these changes

2024-05-15 15:12 UTC, merged