Adds `Alias` Statement
rokucommunity/brighterscript pull request #1151
Opened 2024-05-02 19:27 UTC by markwpearce

This is pretty cool!

`alias` provides a way to work around variable name shadowing... but as a side effect, it also give a way to shorthand just about any property/function you want.

```BrighterScript
alias get2 = get

namespace http
    'Do an HTTP request
    sub get()
        print get2.aa().data 'using `get2` aliased symbol here. it's now clear which item we intended to use
    end sub
end namespace

namespace get
    function aa()
        return {
            data: "abc"
        }
    end function
end namespace
```

transpiles to

```BrightScript
sub http_get()
    print get_aa().data
end sub

sub get_aa()
    return {
        data: "abc"
    }
end sub
```

it also allows this ... which is cool?:

```
alias lc = lcase
alias co = createObject

sub getModelTypeLower()
   lc(co("roDeviceInfo").getModelType())
end sub
```

it also allows this ... which is also cool?:

```
alias abgdz = alpha.beta.gamma.delta.zeta

sub foo()
   print abgdz.someConst
end sub
```

2024-05-02 19:28 UTC, markwpearce commented
addresses #1113

2024-05-03 18:31 UTC, TwitchBronBron requested changes
Looks great! Just a few small things

2024-05-03 18:31 UTC, TwitchBronBron commented on src/files/BrsFile.spec.ts
> +            it('can deep alias a namespaced thing', async () => {
Can you add a test for aliased class? And make sure we can `new` the class using the alias name? And that it transpiles properly?
i.e.:
```
alias Person2 = Person
sub test()
     dude = new Person2()
end sub
```

2024-05-04 01:51 UTC, markwpearce commented
Updated to fixes review comments.

2024-05-06 14:45 UTC, TwitchBronBron approved these changes

2024-05-06 15:51 UTC, merged