Feature/symbol table
rokucommunity/brighterscript pull request #380
Opened 2021-03-31 13:14 UTC by markwpearce

Adds the `SymbolTable` class, and builds the symbol table from assignments and function names

2021-03-31 19:00 UTC, TwitchBronBron requested changes
Looks great! I have items that need to be addressed.

2021-03-31 19:00 UTC, TwitchBronBron commented on src/SymbolTable.ts
> +export interface BscSymbol {
Can you move this interface to the bottom so the primary export (i.e. SymbolTable) is at the top of the file?

2021-03-31 19:00 UTC, TwitchBronBron commented on src/SymbolTable.ts
> +     * @param {Identifier} name
You don't need to specify the data type (i.e. `{Identifier}`) with jsdocs in typescript...any docs generator would infer the type from the typed parameters below.

2021-03-31 19:00 UTC, TwitchBronBron commented on src/SymbolTable.ts
> +            this.symbols.set(key, value);
We should merge the symbols, not overwrite them. Call `this.addSymbol` instead.

2021-03-31 19:00 UTC, TwitchBronBron commented on src/parser/Parser.spec.ts
> +        it('does not know about symbols declared in parent functions', () => {
Nice test!

2021-03-31 19:00 UTC, TwitchBronBron commented on src/parser/Parser.spec.ts
> +    describe('symbolTable', () => {
Can you add tests to ensure `for` and `for-each` loop variable are included in the symbol table? 

`for i = 0 to 10 step 1` and `for each thing in items`

2021-04-01 10:42 UTC, TwitchBronBron commented on src/SymbolTable.ts
> +export interface BscSymbol {
Let's change this interface to:
```
export interface BscSymbol {
    name: string;
    range: Range;
    type: BscType;
}
```

That way, we can add any string-based symbol as long as we can generate a range for it, such as namespaces which would have multiple identifiers, or other future symbols we haven't realized yet. 

```
          |identifier | dot | identifier |
namespace    Animals     .       Dogs
```

2021-04-01 10:43 UTC, TwitchBronBron commented on src/SymbolTable.ts
> +    addSymbol(name: Identifier, type: BscType) {
Based on [this comment](https://github.com/rokucommunity/brighterscript/pull/380/files#r605556107), change this method signature to:
```
addSymbol(name: string, type: BscType, range?: Range) {
```

2021-04-01 13:20 UTC, markwpearce commented
Not sure why the mac build failed? I assume some sort of external issue

2021-04-01 19:16 UTC, TwitchBronBron commented
> Not sure why the mac build failed? I assume some sort of external issue - I have a Mac, and it builds/lints/runs fine on my machine

The GitHub actions mac builds sometimes have issues. I re-ran them and everything is passing now.

2021-04-01 19:16 UTC, TwitchBronBron commented
This is a great step forward! Per our conversations in slack, we still have a few scope-related changes to make before the target PR can be merged. However, I'm happy with the current progress of this PR so I'm merging it.

2021-04-01 19:16 UTC, merged