Refactor try-catch statement
rokucommunity/brighterscript pull request #514
Opened 2022-02-13 10:12 UTC by elsassph

Split the catch part into its a child statement of the try statement in order to facilitate source walking (for linting).
Add missing reflection methods.

2022-02-13 14:00 UTC, chrisdp commented on src/parser/Statement.ts
> +            ...(this.catchBranch?.transpile(state) ?? [])
Based on a short convo in slack it sounds like this is something we could think about later.

2022-02-13 14:00 UTC, chrisdp approved these changes

2022-02-14 12:48 UTC, TwitchBronBron requested changes

2022-02-14 12:48 UTC, TwitchBronBron commented on src/parser/Statement.ts
> +        public catchToken: Token,
I've been trying to store all tokens in a single `tokens` property. can you do the same? See [enum member statement](https://github.com/rokucommunity/brighterscript/blob/b222bce315bffa49d28a3576e3991e86d9df8213/src/parser/Statement.ts#L2181) for an example. The `catchToken` and `exceptionVariable` should both go into `.tokens`

2022-02-14 12:48 UTC, TwitchBronBron commented on src/parser/Statement.ts
> +            ...(this.catchBranch?.transpile(state) ?? [])
I think we should generate code without syntax errors as much as possible, so I think we _should_ gracefully generate an empty catch statement even if it's missing in the source. However, for now, we should also emit a diagnostic saying something like "missing catch statement". 

A future discussion can be had for whether we make catch statements optional.

2022-02-23 14:30 UTC, TwitchBronBron commented
@elsassph when you get a chance, could you review my suggestions?

2022-03-24 14:50 UTC, merged